provider:
  linux: github_actions
  osx: github_actions
  win: github_actions
        # This line prevents the tool from trying to ping Azure
azure:
  force: false

channel_sources:
- cryoem, conda-forge            # [unix]
- cryoem, conda-forge, defaults  # [win]
channel_targets:
- cryoem main
__cuda:
  - "12.8"
__linux:
    - "1"

ui:
  - gui
  - nogui

pyqt:
  - 5
pyopengl:
  - 3.1.7
nodejs:
  - '*'

pin_run_as_build:
  pyqt:
    max_pin: x.x
#  pyopengl:
#    max_pin: x.x

ignore_version:
  - nodejs
