{% set build = 5 %}

{% if ui == "gui" %}
{% set ver_minor = 1 %}
{% else %}
{% set ver_minor = 0 %}
{% endif %}

package:
  name: eman-deps
  version: "34.{{ ver_minor }}"

build:
  number: {{ build }}
  noarch: python
  string: "{{ ui }}_{{ build }}"

requirements:
  host:
    - python

  run:
    - python

    # GUI dependencies
    - pyqt           # [ui == "gui"]
    - pyopengl >=3.1 # [ui == "gui"]

    # scientific stack
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - matplotlib

    # ML
    - tensorflow >=2.18

    # interactive environment
    - ipython
    - ipywidgets
    - jupyterlab

    # utilities
    - tqdm
    - future
    - configparser

    # system libs
    - boost
    - fftw
    - ftgl
    - freetype
    - gsl
    - hdf5 >=1.12
    - libjpeg-turbo
    - libtiff
    - libpng
    - zlib

test:
  imports:
    - numpy
    - scipy
    - sklearn
    - pandas

about:
  summary: Meta-package for EMAN2 dependencies
  license: BSD-3-Clause
