{% set build = 0 %}

package:
    name: eman-deps
    version: '29.5'

build:
    # prioritize gui variant via build number
    {% if ui == 'gui' %}
    {% set build = build + 100 %}
    {% endif %}
    number: {{ build }}
    skip: True  # [win32]
    skip: True  # [ui == 'nogui']
    skip: True  # [py<37]

    # add build string so packages can depend on
    # gui or nogui variants explicitly:
    # `pkg * gui_*` for any gui
    # `pkg * nogui_*` for no gui
    string: "{{ ui }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
    host:
        - pyqt                              # [ui == 'gui']
        - pyopengl                          # [ui == 'gui']
        - cmake

        - matplotlib
        - scipy
        - ipython
        - scikit-learn
        - pandas
        - tensorflow-gpu 2                  # [linux]
        - cudatoolkit                       # [linux]
        - cudnn          7                  # [linux]
        - tensorflow     2                  # [osx or win]
        - bsddb3
        - pydusa                            # [not win]
        - nose
        - future
        - configparser
        - tqdm

        - python
        - boost
        - fftw           3.*  mpi_openmpi_*  # [not win]
        - fftw           3.*  nompi_*        # [win]
        - numpy
        - ftgl
        - freetype
        - gsl
        - hdf5
        - jpeg
        - libtiff
        - libpng
        - libdb
        - zlib
        - openmpi        4                     # [not win]

    run:
        {% for package in resolved_packages('host') %}
        - {{ package }}
        {% endfor %}

test:
  files:
    - test_imports.py
    - test_imports_future.py
    - test_imports_gui.py                   # [ui == 'gui']
    - test_imports_pydusa.py                # [not win]
  commands:
    - echo "TESTING eman-deps"
    - cmake --version
    - python test_imports.py
    - python test_imports_future.py
    - python test_imports_gui.py            # [ui == 'gui']
    - python test_imports_pydusa.py         # [not win]

about:
  summary: Meta-package for eman2 dependencies
