{% set build = 0 %}

# prioritize gui variant via minor version
{% if ui == 'gui' %}
{% set ver_minor = 1 %}
{% else %}
{% set ver_minor = 0 %}
{% endif %}

package:
    name: eman-deps
    version: "30.{{ ver_minor }}"

build:
    number: {{ build }}
    skip: True  # [win32]
    skip: True  # [py!=37]
    skip: True  # [ui=='nogui']

    # add build string so packages can depend on
    # gui or nogui variants explicitly:
    # `pkg * gui_*` for any gui
    # `pkg * nogui_*` for no gui
    string: "{{ ui }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
    build:
      - {{ compiler('c') }}
      - sysroot_linux-64 2.17               # [linux64]

    host:
      - pyqt           5.*                # [ui == 'gui']
      - pyopengl       3.1.5              # [ui == 'gui']
      - cmake        >=3.14

      - matplotlib
      - scipy
      - ipython
      - scikit-learn
      - pandas
      - tensorflow-gpu 2.*                # [linux]
      - tensorflow     2.*                # [osx or win]
      - bsddb3
      - pydusa         3.0                # [not win]
      - nose
      - future
      - configparser
      - tqdm
      - jupyterlab
      - nodejs         16

      - python
      - boost
      - fftw           *      mpi_openmpi_*  # [not win]
      - fftw           *      nompi_*        # [win]
      - numpy          1.18
      - ftgl
      - freetype
      - gsl
      - hdf5
      - jpeg
      - libtiff
      - libpng
      - zlib

    run:
      - pyqt           5.*                # [ui == 'gui']
      - pyopengl       3.1.5              # [ui == 'gui']
      - cmake        >=3.14

      - matplotlib
      - scipy
      - ipython
      - scikit-learn
      - pandas
      - tensorflow-gpu 2.*                # [linux]
      - tensorflow     2.*                # [osx or win]
      - bsddb3
      - pydusa         3.0                # [not win]
      - nose
      - future
      - configparser
      - tqdm
      - jupyterlab
      - nodejs         16

      - python
      - boost
      - fftw           *      mpi_openmpi_*  # [not win]
      - fftw           *      nompi_*        # [win]
      - numpy          1.18
      - ftgl
      - freetype
      - gsl
      - hdf5
      - jpeg
      - libtiff
      - libpng
      - zlib

test:
  files:
    - test_imports.py
    - test_imports_future.py
    - test_imports_gui.py                   # [ui == 'gui']
    - test_imports_pydusa.py                # [not win]
  commands:
    - echo "TESTING eman-deps"
    - cmake --version
    - python test_imports.py
    - python test_imports_future.py
    - python test_imports_gui.py            # [ui == 'gui']
    - python test_imports_pydusa.py         # [not win]

about:
  summary: Meta-package for eman2 dependencies
