{% set build = 0 %}

# prioritize gui variant via minor version
{% if ui == 'gui' %}
{% set ver_minor = 1 %}
{% else %}
{% set ver_minor = 0 %}
{% endif %}

package:
    name: eman-deps
    version: "33.{{ ver_minor }}"

{% if win %}
{% set numpy = '1.20' %}
{% endif %}

build:
    number: {{ build }}
    skip: True  # [py!=39]

    # add build string so packages can depend on
    # gui or nogui variants explicitly:
    # `pkg * gui_*` for any gui
    # `pkg * nogui_*` for no gui
    string: "{{ ui }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
    build:
      - {{ compiler('c') }}
      - sysroot_linux-64 2.17               # [linux64]

    host:
      - pyqt                                # [ui == 'gui']
      - pyopengl                            # [ui == 'gui']
      - cmake        >=3.14

      - ipywidgets
      - matplotlib
      - scipy
      - ipython
      - scikit-learn
      - pandas
      - tensorflow
      - pydusa                              # [not win and (build_platform == target_platform)]
      - nose
      - future
      - configparser
      - tqdm
      - jupyterlab
      - nodejs

      - python
      - boost
      - fftw
      - numpy                               # [unix]
      - numpy          {{ numpy }}          # [win]
      - ftgl
      - freetype
      - gsl
      - hdf5
      - jpeg
      - libtiff
      - libpng
      - zlib

    run:
      - pyqt                                # [ui == 'gui']
      - pyopengl                            # [ui == 'gui']
      - cmake        >=3.14

      - ipywidgets
      - matplotlib
      - scipy
      - ipython
      - scikit-learn
      - pandas
      - tensorflow
      - pydusa                              # [not win and (build_platform == target_platform)]
      - nose
      - future
      - configparser
      - tqdm
      - jupyterlab
      - nodejs

      - python
      - boost
      - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
      - ftgl
      - freetype
      - gsl
      - hdf5
      - jpeg
      - libtiff
      - libpng
      - zlib

test:
  requires:
    - openssh                               # [not win]
  files:
    - test_imports.py
    - test_imports_future.py
    - test_imports_gui.py                   # [ui == 'gui']
    - test_imports_pydusa.py                # [not win]
    - test_pydusa.py                        # [not win]
  commands:
    - echo "TESTING eman-deps"
    - python -c "import numpy; assert numpy.version.version.startswith('{{ numpy }}'), 'NumPy version expected to be {{ numpy }}'"
    - cmake --version
    - python test_imports.py
    - python test_imports_future.py
    - python test_imports_gui.py            # [ui == 'gui']
    - python test_imports_pydusa.py         # [not win]
    - mpirun -n 2 --oversubscribe python test_pydusa.py  # [not win]

about:
  summary: Meta-package for eman2 dependencies
