appveyor:
  secure:
    BINSTAR_TOKEN: IKCEuGznkMky7EruV0O+eJIN6T8lOx/ALYBXKlouPz40BKPfqOky24LFZpTlS/5Y

channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: eman-deps-feedstock

provider:
  linux: circle
  osx: github_actions
  win: github_actions

os_version:
  linux_64: cos7
